library(xtable)
options(width=240)
options(xtable.caption.placement="top")
options(xtable.booktabs=T)
#options(xtable.sanitize.text.function=function(x){x})
options(xtable.sanitize.text.function=function(x){ sub("_","",x) })
#options(xtable.sanitize.text.function=sanitize)
options(xtable.table.placement="t")
options(xtable.include.rownames=F)
options(xtable.math.style.exponents=T)
options(xtable.math.style.negative=T)
options(xtable.table.placement="ht")
